import type { ServerResponse } from "node:http";
import { authenticateToken, parseAuthToken } from "../services/auth.js";
import { generateReplies, ProviderError } from "../services/aiProvider.js";
import {
  assertModelAllowed,
  getModelPricing,
  MODEL_ALLOWLIST_UNAVAILABLE_MESSAGE,
} from "../services/modelCatalog.js";
import { consumeRateLimit, refundRateLimit } from "../services/rateLimit.js";
import { assertSafeRequest } from "../services/safety.js";
import { readJsonBody, sendError, sendJson } from "../serverUtils.js";
import {
  ENGAGEMENT_OBJECTIVES,
  TONES,
  type GenerateReplyRequest,
  type GenerateReplyResponse,
  type Tone,
} from "../types/index.js";

type GenerateFn = (input: GenerateReplyRequest) => Promise<{
  texts: string[];
  tone: Tone;
  model?: string;
  usage?: { promptTokens: number; completionTokens: number } | null;
}>;

// getModelPricing() can fall through to a live OpenRouter fetch (up to its
// own 10s timeout) when the hourly catalog cache is cold — most exposed on
// the AI_DEFAULT_PROVIDER=openai path, which never otherwise touches the
// catalog, for a lookup that's guaranteed to miss anyway (OpenAI's bare
// model IDs don't match OpenRouter's "openai/..."-prefixed catalog IDs).
// Cost estimation is best-effort and secondary to the replies (already
// generated by this point) — bound how long it can hold up the response,
// independent of modelCatalog's own timeout, which other callers
// (the model dropdown, the reasoning-parameter check) need to keep longer.
const PRICING_LOOKUP_TIMEOUT_MS = 3_000;

async function resolveTokenUsage(
  model: string,
  usage: { promptTokens: number; completionTokens: number } | null | undefined,
): Promise<GenerateReplyResponse["tokenUsage"]> {
  if (!usage) return undefined;
  const pricing = await Promise.race([
    getModelPricing(model),
    new Promise<null>((resolve) => setTimeout(() => resolve(null), PRICING_LOOKUP_TIMEOUT_MS)),
  ]);
  const estimatedCostUsd = pricing
    ? usage.promptTokens * pricing.prompt + usage.completionTokens * pricing.completion
    : undefined;
  return { promptTokens: usage.promptTokens, completionTokens: usage.completionTokens, estimatedCostUsd };
}

function optionalString(value: unknown, maxLength: number): string | undefined {
  if (value === undefined || value === null || value === "") return undefined;
  if (typeof value !== "string" || value.length > maxLength) return undefined;
  return value.trim() || undefined;
}

function optionalHttpUrl(value: unknown, maxLength: number): string | undefined {
  const candidate = optionalString(value, maxLength);
  if (!candidate) return undefined;
  try {
    const url = new URL(candidate);
    return url.protocol === "http:" || url.protocol === "https:" ? candidate : undefined;
  } catch {
    return undefined;
  }
}

function optionalLanguageTag(value: unknown): string | undefined {
  const candidate = optionalString(value, 35);
  if (!candidate || candidate.toLowerCase() === "und") return undefined;
  try {
    return Intl.getCanonicalLocales(candidate)[0];
  } catch {
    throw new Error("sourceLanguage must be a valid BCP 47 language tag.");
  }
}

export function validateGenerateRequest(value: unknown): GenerateReplyRequest {
  if (!value || typeof value !== "object") throw new Error("Request body must be an object.");
  const body = value as Record<string, unknown>;
  // postText is optional when imageUrls carries the content instead (an
  // image-only post with no caption) — validated together further down,
  // once imageUrls has also been parsed.
  const postText = optionalString(body.postText, 10_000);
  if (
    typeof body.tone !== "string" ||
    (body.tone !== "auto" && !TONES.includes(body.tone as never))
  ) {
    throw new Error(`tone must be "auto" or one of: ${TONES.join(", ")}.`);
  }

  if (
    body.objective !== undefined &&
    (typeof body.objective !== "string" || !ENGAGEMENT_OBJECTIVES.includes(body.objective as never))
  ) {
    throw new Error(`objective must be omitted or one of: ${ENGAGEMENT_OBJECTIVES.join(", ")}.`);
  }

  const count = body.count === undefined ? 3 : body.count;
  if (!Number.isInteger(count) || Number(count) < 1 || Number(count) > 3) {
    throw new Error("count must be an integer between 1 and 3.");
  }

  // 25,000 matches X Premium+'s own post limit — Free/Premium accounts have
  // lower caps (280/4,000), but that's a per-account plan choice the caller
  // makes, not something the backend needs to enforce.
  const maxLength = body.maxLength === undefined ? 220 : body.maxLength;
  if (
    maxLength !== "auto" &&
    (!Number.isInteger(maxLength) || Number(maxLength) < 50 || Number(maxLength) > 25_000)
  ) {
    throw new Error('maxLength must be "auto" or an integer between 50 and 25000.');
  }

  const useEmoji = body.useEmoji === undefined ? true : body.useEmoji;
  if (typeof useEmoji !== "boolean") {
    throw new Error("useEmoji must be a boolean.");
  }

  const replyLanguage = body.replyLanguage === undefined ? "post" : body.replyLanguage;
  if (replyLanguage !== "post" && replyLanguage !== "en") {
    throw new Error('replyLanguage must be "post" or "en".');
  }

  const sourceLanguage = optionalLanguageTag(body.sourceLanguage);

  let blockedTerms: string[] | undefined;
  if (body.blockedTerms !== undefined) {
    if (!Array.isArray(body.blockedTerms) || body.blockedTerms.length > 50) {
      throw new Error("blockedTerms must contain at most 50 items.");
    }
    const seen = new Set<string>();
    blockedTerms = [];
    for (const item of body.blockedTerms) {
      const term = optionalString(item, 80)?.trim();
      if (!term) throw new Error("Each blockedTerms item must be a non-empty string of at most 80 characters.");
      const key = term.normalize("NFKC").toLowerCase();
      if (seen.has(key)) continue;
      seen.add(key);
      blockedTerms.push(term);
    }
    if (blockedTerms.length === 0) blockedTerms = undefined;
  }

  let visibleThreadText: string[] | undefined;
  if (body.visibleThreadText !== undefined) {
    if (!Array.isArray(body.visibleThreadText) || body.visibleThreadText.length > 5) {
      throw new Error("visibleThreadText must contain at most 5 items.");
    }
    visibleThreadText = body.visibleThreadText.map((item) => {
      const text = optionalString(item, 2_000);
      if (!text) throw new Error("Each visibleThreadText item must be a non-empty string.");
      return text;
    });
  }

  let imageUrls: string[] | undefined;
  if (body.imageUrls !== undefined) {
    if (!Array.isArray(body.imageUrls) || body.imageUrls.length > 4) {
      throw new Error("imageUrls must contain at most 4 items.");
    }
    imageUrls = body.imageUrls.map((item) => {
      const url = optionalHttpUrl(item, 2_000);
      if (!url) throw new Error("Each imageUrls item must be a valid http(s) URL.");
      return url;
    });
    if (imageUrls.length === 0) imageUrls = undefined;
  }

  if (!postText && !imageUrls) {
    throw new Error("Either postText or imageUrls must be provided.");
  }

  return {
    postText: postText ?? "",
    sourceLanguage,
    replyLanguage,
    tone: body.tone as GenerateReplyRequest["tone"],
    objective: body.objective as GenerateReplyRequest["objective"],
    count: Number(count),
    maxLength: maxLength === "auto" ? "auto" : Number(maxLength),
    useEmoji,
    authorHandle: optionalString(body.authorHandle, 100),
    authorName: optionalString(body.authorName, 200),
    postUrl: optionalString(body.postUrl, 2_000),
    imageUrls,
    visibleThreadText,
    extraInstruction: optionalString(body.extraInstruction, 500),
    blockedTerms,
    model: optionalString(body.model, 200),
  };
}

export async function generateReplyRoute(
  request: NodeJS.ReadableStream & { headers?: Record<string, string | string[] | undefined> },
  response: ServerResponse,
  generate: GenerateFn = generateReplies,
): Promise<void> {
  const authHeader = request.headers?.authorization;
  const authToken = parseAuthToken(
    Array.isArray(authHeader) ? authHeader[0] : authHeader,
  );
  if (!authToken) {
    sendError(response, 401, "AUTH_REQUIRED", "Bearer token is required.");
    return;
  }

  const user = authenticateToken(authToken);
  if (!user) {
    sendError(response, 403, "INVALID_TOKEN", "Bearer token is invalid.");
    return;
  }

  let input: GenerateReplyRequest;
  try {
    input = validateGenerateRequest(await readJsonBody(request));
    assertSafeRequest(input.extraInstruction);
    await assertModelAllowed(input.model);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Invalid request.";
    if (message === MODEL_ALLOWLIST_UNAVAILABLE_MESSAGE) {
      sendError(response, 502, "PROVIDER_ERROR", message);
      return;
    }
    const code = message === "Invalid JSON body." ? "INVALID_JSON" :
      message === "Request body is too large." ? "VALIDATION_ERROR" :
      message === "Requested instruction is not allowed." ? "UNSAFE_REQUEST" :
      "VALIDATION_ERROR";
    sendError(response, code === "UNSAFE_REQUEST" ? 422 : 400, code, message);
    return;
  }

  const reservedAt = new Date();
  const usage = consumeRateLimit(user.token, user.plan, reservedAt);
  if (!usage.allowed) {
    if (usage.retryAfterSeconds) {
      response.setHeader("Retry-After", String(usage.retryAfterSeconds));
    }
    const message = usage.limitedBy === "minute"
      ? "Per-minute generation limit reached."
      : "Daily generation limit reached.";
    sendError(response, 429, "RATE_LIMITED", message);
    return;
  }

  try {
    const { texts, tone, model, usage: tokenUsageRaw } = await generate(input);
    const resolvedModel = model ?? input.model ?? process.env.AI_DEFAULT_MODEL ?? "unknown";
    const payload: GenerateReplyResponse = {
      replies: texts.map((text, index) => ({
        id: `reply_${index + 1}`,
        text,
        tone,
      })),
      usage: { remainingToday: usage.remainingToday, plan: user.plan },
      model: resolvedModel,
      tokenUsage: await resolveTokenUsage(resolvedModel, tokenUsageRaw),
    };
    sendJson(response, 200, payload);
  } catch (error) {
    refundRateLimit(user.token, reservedAt);
    if (error instanceof ProviderError) {
      const code = error.statusCode === 503 ? "PROVIDER_NOT_CONFIGURED" : "PROVIDER_ERROR";
      sendError(response, error.statusCode, code, error.message);
      return;
    }
    console.error("Unhandled generate error", error);
    sendError(response, 500, "INTERNAL_ERROR", "Reply generation failed.");
  }
}
